---

name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile templates
      uses: cuchi/jinja2-action@v1.1.0
      with:
        template: terraform.tf.j2
        output_file: terraform.tf
        strict: true
        variables: |
          access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          state_bucket=${{ secrets.STATE_BUCKET }}
          region=${{ secrets.REGION }}

    - name: Compile templates
      uses: cuchi/jinja2-action@v1.1.0
      with:
        template: terraform.tfvars.j2
        output_file: terraform.tfvars
        strict: true
        variables: |
          region=${{ secrets.REGION }}
          vpc_cidr_block=${{ secrets.VPC_CIDR_BLOCK }}

    - name:
      run: cat terraform.tfvars

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
    
    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
